# Generated by Django 4.2.4 on 2023-11-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('title',)},
        ),
    ]
